### ISSUE TITLE
One dockblock per file?

### ISSUE THREAD

**Issue by hananmalka** [eugene-manuilov/jest-runner-groups#24]
Can I set several dockblock per file? 
I mean, I have file with several describes and I want to define each describe in different group. 

Can I do it?
Currently I have 2 describes in one file:

```/**
 * @group sanity
 */
describe("Sanity", () => {});

/**
 * @group regression
 */
describe("Regression", () => {});```

If i'm running `--group=sanity`
it's still runs regression tests as well.

**Comment by eugene-manuilov** [comment]
Hi @hananmalka,

unfortunately, you can't set groups per describe block because this runner is responsible for filtering files only. Jest uses test runners to control which tests should be executed in a certain file.

What you can do is split your describe blocks into separate files and use different group tags there.
