### ISSUE TITLE
Clarify the added value

### ISSUE THREAD

**Issue by goldbergyoni** [eugene-manuilov/jest-runner-groups#3]
Thanks for the contribution.

Help me realize the added-value: one could just a tag to the describe block:
```
describe('Some description #any-tag')
```
And then grep for this tag using the built-in -t flag:
```jest -t any-tag```

What added value does this repo bring over the example above?

**Comment by eugene-manuilov** [comment]
Hi @goldbergyoni 

`-t` also works and can be an option if it works for you but it has a few drawbacks if you need more advanced usage. 

First of all `-t` requires you to put your tag into a test/describe name. What if you need to add more than one tag? Let's say you need to add the following tags: `#database`, `#preprod`, `#integrational`, `#components/sidebar/Search`? Then you will have something like this:

```javascript
describe( 'Check sidebar search #database #preprod #integrational #components/sidebar/Search', () => {
    // ...
} );
```

Quite messy, isn't it? You will get your test names bloated and hard to read.

Second, `-t` accepts a regular expression and if you need to run two and more different groups, you will need to combine group names into one big regular expression. Usually writing a regular expressions in the terminal is quite cumbersome process.

Third, since `-t` expects a regular expression, there might be a case when a provided regular expression matches what you don't expect.

So, answering your question, this repo brings a bit of clarity in grouping and running your groupped tests. This repo is not an ultimate approach to group and run groupped tests, there are other approaches for sure.

**Comment by tihuan** [comment]
Hey there! Thanks for the amazing tool 👍

It's currently my impression that the runner groups only works at the file level, instead of `describe`, `test`, `it` level. Is that correct?

E.g.,

```ts
// Following tests in the same file

/**
 * @group smoke
 */
describe('foo', () => { ... })

/**
 * @group smoke
 * @group acceptance
 */
describe('bar', () => { ... })
```

And I remember `jest --group=smoke` wouldn't run both `foo` and `bar`, and `jest --group=acceptance` wouldn't just run `bar` too

If so, has such feature been considered? Thank you!

**Comment by eugene-manuilov** [comment]
Thanks @tihuan! 

Unfortunately, a [runner](https://jestjs.io/docs/en/configuration#runner-string) can't control which tests to run in a file, it can only control which files to run. A [test runner](https://jestjs.io/docs/en/configuration#testrunner-string) is responsible for running particular tests in the file. I need to think about it a little bit more.

**Comment by tihuan** [comment]
Hi @eugene-manuilov ! Ahh I see, thanks so much for pointing out the distinction 🙏 

If a test runner can control particular tests, then it almost sounds like we could leverage `jest-circus` to achieve the goal? (Given that `jest-circus` exposes jest test events and we can extend `jest-environment-puppeteer` to handle desired events, such as `start_describe_definition` and `add_test`, etc. [full event list](https://github.com/facebook/jest/blob/master/packages/jest-types/src/Circus.ts))

For example, in order to set up taking a screenshot for each failed test after N retries, we could do:

```ts
module.exports = {
  testRunner: 'jest-circus/runner',
  ...
  testEnvironment: './jest/env.js',
}
```

```ts
// ./jest/env.js

const PuppeteerEnvironment = require('jest-environment-puppeteer')
require('jest-circus')

const takeScreenshot = require('./takeScreenshot')

const RETRY_ATTEMPTS = 2

class Environment extends PuppeteerEnvironment {
  async handleTestEvent(event, state) {
    if (event.name === 'error') {
      console.log('error', JSON.stringify(event))
    }

    if (event.name === 'test_fn_failure' || event.name === 'hook_failure') {
      // We only want to take screenshot on the last try
      if (state.currentlyRunningTest.invocations <= RETRY_ATTEMPTS) return

      console.log('===> Failure event\n', event)

      await takeScreenshot(state.currentlyRunningTest.name, this.global.page)
    }
  }
}

module.exports = Environment
```

So I'm thinking perhaps if there's a way to parse group tag comment for each test and add such info to the test's metadata, then we could (hopefully) use `start_describe_definition` and `add_test` events to decide whether to skip a describe or a test accordingly?
